### ISSUE TITLE
Missing INSTALL file

### ISSUE THREAD

**Issue by matovitch** [autotools-mirror/libtool#1]
Hello,

The README.md mention an INSTALL file with a link which I suppose was valid at some point but isn't anymore.

Best Regards,

Camille

**Comment by TimothyGu** [comment]
Hi, this is just a mirror so no support is provided. You may want to instead contact the folks actually maintaining libtool: https://www.gnu.org/software/libtool/contribute.html.

However, as a friendly tip, you might find INSTALL to be automatically generated after running the `./bootstrap` script in the cloned source tree, assuming you have autotools installed on your computer already in order to run the script.
